# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "B.Honnef Website"
title_separator: "-"
email: contact@honnef.dev
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
github_username: ehonnef
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "default"
minimal_mistakes_skin2: "dark"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Sao_Paulo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
locale: "en"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "B.Honnef"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Yup! I like programming :)"
  github : "eHonnef"
  rawemail: "contact@honnef.dev"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "/portfolio/"

repository: "eHonnef/ehonnef.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"

comments:
  provider: "giscus"
  giscus:
    repo_id              : "R_kgDOG6gFmA" # Shown during giscus setup at https://giscus.app
    category_name        : "Posts comments" # Full text name of the category
    category_id          : "DIC_kwDOG6gFmM4CZDrj" # Shown during giscus setup at https://giscus.app
    discussion_term      : "title" # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : "1" # '1' for enabled (default), '0' for disabled
    theme                : "light" # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ehonnef"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
  # _smallportfolio
  - scope:
      path: ""
      type: smallportfolio
    values:
      layout: single
      author_profile: true
      share: true
  # _uniportfolio
  - scope:
      path: ""
      type: uniportfolio
    values:
      layout: single
      author_profile: true
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  smallportfolio:
    output: true
    permalink: /:collection/:path/
  uniportfolio:
    output: true
    permalink: /:collection/:path/